### ISSUE TITLE
CKEditor can not read bootstrap.min.css

### ISSUE THREAD

**Issue by VeNick-GS** [risingisland/GetSimpleCMS-CE-3.3.19.1#1]
Hi, when I'm editing page there is an error visible in the console like: 
"Failed to load resource: the server responded with a status of 404 (Not Found)"
 or 
"GET https://mysite.com/path/to/bootstrap/css/bootstrap.min.css net::ERR_ABORTED 404".
Source is in the line 78 of the file ckeditor.js
Seems there is incorrect path to bootstrap.min.css written.
How to correct it?

**Comment by risingisland** [comment]
Hello @VeNickov 
There is no reference to "bootstrap.min.css" in "ckeditor.js" nor in GetSimple.
Were you trying to add bootstrap in via gsconfig.php or in a theme?
Sorry, I am not seeing this error anywhere. Is this on a default install or trying to use a new template?

**Comment by VeNick-GS** [comment]
Hello, @risingisland 
Just made default install of the SG3.3.19_pre in to the clean server. There is the same error message in the Chrome console. Any additional plugings or themes were installed. 
When CRKeditor is off then there is no errors.

**Comment by VeNick-GS** [comment]
Hello, @risingisland 
Source of the error is in the code in line 17 of file /admin/template/js/ckeditor/plugins/cmsgrid/plugin.js
This is configuration of the path to botstrap.min.css
In default installation there is no bootstrap and therefor we receive an error message.

**Comment by risingisland** [comment]
Thank you for the information. I think that is one of the new plug-ins added by my partner. In FF I didn't see any error. Will look at this tomorrow.
In gsconfig, change the editor to island and see if that is OK. You can edit this file directly or via setting you will find a new sidebar menu to do this from within the admin. Thanks for the testing, we hope to release this in the CE site this week sometime.

**Comment by risingisland** [comment]
Fixed.
