### ISSUE TITLE
RU language for CKE plugin cmsgrid

### ISSUE THREAD

**Issue by VeNick-GS** [risingisland/GetSimpleCMS-CE-3.3.19.1#2]
Hello, @risingisland 

How to translate CKE plugin cmsgrid to other language?
I have prepared and uploaded the new file ru.js but it is not working.
Thanks!

**Comment by risingisland** [comment]
Pleases post the lang file here so I can add it.
I will take a look at this and let you know.

**Comment by VeNick-GS** [comment]
`"use strict"

CKEDITOR.plugins.setLang( 'cmsgrid', 'ru', {
	btnAddGrid: 'Добавить индивидуальный макет',
	btnChangeGrid: 'Изменить пользовательский макет',
	btnAddRow: 'Добавить строку',
	btnDeleteRow: 'Удалить строку',
	btnExpandRightCol: 'Развернуть правый столбец',
	btnExpandLeftCol: 'Развернуть левый столбец',
	btnSwapCols: 'Поменять местами столбцы',
	stepOneText: '1.) Выберите макет',
	stepTwoText: '2.) Введите количество строк',
	evenColText: 'Равные столбцы',
	largeRightColText: 'Увеличить правые столбцы',
	largeLeftColText: 'Увеличить левые столбцы',
	addTab: 'Добавить макет',
	windowTitle: 'Добавить индивидуальный макет',
	layoutError:  'Выберите макет и количество строк',
	layout48Text: 'макет 33% слева и 66% справа',
	layout39Text: 'макет 25% слева и 75% справа',
	layout210Text:  'макет 16% слева и 83% справа',
	layout84Text:  'макет 66% слева и 33% справа',
	layout93Text: 'макет 75% слева и 25% справа',
	layout102Text: 'макет 83% слева и 16% справа',
	layout66Text: '2 одинаковых столбца',
	layout444Text: '3 одинаковых столбца',
	layout3333Text: '4 одинаковых столбца'
} );`

**Comment by risingisland** [comment]
Next time you can just drag the file into post. It has been updated/added.
