### ISSUE TITLE
Plugin i18n Special page

### ISSUE THREAD

**Issue by VeNick-GS** [risingisland/GetSimpleCMS-CE-3.3.19.1#3]
Hi @risingisland 
There an issue with configuartion of the plugin i18n Special page. Plugin was downloaded from your Repository.
When I create new special page type (or edit special page type template) it is not possible to switch plugin configuartion menu (General>Fields>View>Search) 
Thanks!

**Comment by risingisland** [comment]
Hello @VeNickov 
This is just a copy from mvlcek on the GS site, not our creation, so you may want to post a message on the forum to see if he has any updates. You will probably want to let him know what version of php you are using and any error messages.
http://get-simple.info/forums/showthread.php?tid=2747

**Comment by risingisland** [comment]
I just took a look too. Yes, it has some problem with both php 7.4 & 8.1.
8.1 doesnt display error, but 7.4 does, so I will take a screen-cap and send it too him, see if he can fix it.

**Comment by risingisland** [comment]
OK, after a bit more testing, I think I may have found the problem. It is with 19pre, not plugin.
Give me some time to troubleshoot this. Thanks for your input.

**Comment by risingisland** [comment]
As far as I can tell, this is a problem with  i18n Special page, if you use any type of custom toolbar for ckEditor.
If you get rid of the custom config in gsconfig, it works fine. I see apart of that plugin that reads from ckEditor.
I dont know if this has been reported to @mvlcek on the forum before. Am going to look to see if there is an easy ulpdate to the plugin. If not will let him know.

**Comment by VeNick-GS** [comment]
Hello @risingisland 
Just tested i18n Special page with GS CE 3.3.18.1 witn MassiveAdmin Theme v. 3.3 on PHP 7.4.8 - plugin is working without errors.

**Comment by risingisland** [comment]
What are your gsconfig.php settings for ckEditor?
In the Pre version, there is a custom toolbar turned on by default.
Comment out lines 61-68, it should work fine too.
It is something to do with how the plugin is using this info. I have left a post in the forum.

**Comment by VeNick-GS** [comment]
There are original gsconfig.php settings from package GS CE 3.3.18.1 with commented 'gseditoroptions'.

**Comment by risingisland** [comment]
Can you paste the gsconfig.php file here, from the version that is not working for you?
Or are you on the forum, and maybe pm me there?

**Comment by VeNick-GS** [comment]
[https://github.com/risingisland/GetSimpleCMS-CE-3.3.19-pre/blob/main/temp.gsconfig.php](url)

**Comment by risingisland** [comment]
OK, please, after install, edit that file gsconfig.php. Comment-out or delete lines 61-68.
It should work, but let me know either way.

**Comment by VeNick-GS** [comment]
Yes, it is work even with the following code:

`# WYSIWYG toolbars (advanced, basic, advanced, island, CEbar or [custom config])
#define('GSEDITORTOOL', "CEbar");'

'# WYSIWYG Editor Options
define('GSEDITOROPTIONS', '
extraPlugins:"fontawesome5,youtube,codemirror,cmsgrid,colorbutton,oembed,simplebutton,spacingsliders"
');`

but in this case it is not possible to use advansed or custom CKE toolbar

**Comment by risingisland** [comment]
Yes, this is a problem with the plugin, not CE.
I have made a post on the forum to see if there is a reply from the dev.
So, until there is a reply or fix from him, other toolbars are not available. 
As far as I know, this isnt something new, it looks like it has been like this for some time.
I will try to look at it some more this week.
Thanks for testing.

**Comment by multicolor-rgb** [comment]
https://github.com/multicolor-rgb/I18n-Special-Pages-CE-Edit This edit fix error toolbar:) Mutlicolor from CE team

**Comment by VeNick-GS** [comment]
Hello @multicolor-rgb 
Just installed and still does not work with PHP 7.4.8.
Error is:
load.php?id=i18n_specialpages&config&edit&template=news:460 Uncaught SyntaxError: Unexpected token ',' (at load.php?id=i18n_specialpages&config&edit&template=news:460:2)

**Comment by VeNick-GS** [comment]
The same error is for creating new type of special page:
load.php?id=i18n_specialpages&config&edit:460 Uncaught SyntaxError: Unexpected token ',' (at load.php?id=i18n_specialpages&config&edit:460:2)

**Comment by multicolor-rgb** [comment]
@VeNickov  install my i18n special pages edit, and remove  "," after "forcePasteAsPlainText : true" on GSCONFIG in section GSEDITOROPTIONS.

**Comment by risingisland** [comment]
Fix confirmed. 
Re-install i18n Special Pages plugin from CE repo.
Remove final comma  "," from line 67 in gsconfig.php

**Comment by VeNick-GS** [comment]
Fixed, Thanks!
